pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_ACCOUNT_ID = '305601180466'
        ECR_REPO = 'app-repository'
        IMAGE_REPO = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
        EKS_CLUSTER = 'eks-cluster'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $IMAGE_REPO:$BUILD_NUMBER ./app
                docker tag $IMAGE_REPO:$BUILD_NUMBER $IMAGE_REPO:latest
                '''
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION \
                | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh '''
                docker push $IMAGE_REPO:$BUILD_NUMBER
                docker push $IMAGE_REPO:latest
                '''
            }
        }

        stage('Deploy to EKS with Helm') {
            steps {
                sh '''
                aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

                kubectl delete svc hello-app --ignore-not-found=true

                helm upgrade --install hello-app helm/hello-app \
                  --set image.repository=$IMAGE_REPO \
                  --set image.tag=$BUILD_NUMBER
                '''
            }
        }
    }
}

